# Generated by Django 3.1.1 on 2023-01-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soliders', '0003_auto_20230105_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='soliders',
            name='sol_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
