# Generated by Django 3.1.1 on 2023-01-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soliders', '0004_soliders_sol_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Letter_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=50)),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('reason', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('sol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soliders.soliders')),
            ],
        ),
    ]
