# Generated by Django 3.1.1 on 2023-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soliders', '0004_soliders_sol_id'),
        ('family', '0002_auto_20230110_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='solider_id',
            field=models.ManyToManyField(to='soliders.Soliders'),
        ),
    ]
