# Generated by Django 3.1.1 on 2023-01-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soliders', '0003_auto_20230105_1726'),
        ('family', '0003_auto_20230105_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='solider_name',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='soliders.soliders'),
            preserve_default=False,
        ),
    ]
