# Generated by Django 4.1.4 on 2022-12-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_purchase', models.DateField()),
                ('checkup', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
