# Generated by Django 4.1.4 on 2022-12-27 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ammon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('lead', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=50)),
                ('ammo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ammon.ammo')),
            ],
        ),
    ]
