# Generated by Django 3.1.1 on 2023-01-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soliders', '0004_soliders_sol_id'),
        ('ammon', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='ammo',
        ),
        migrations.AddField(
            model_name='mission',
            name='ammo',
            field=models.ManyToManyField(to='ammon.Ammo'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soliders.soliders'),
        ),
    ]
