# Generated by Django 3.1.1 on 2023-01-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ammon', '0001_initial'),
        ('missions', '0002_auto_20230113_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='ammo',
        ),
        migrations.AddField(
            model_name='mission',
            name='ammo',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='ammon.ammo'),
            preserve_default=False,
        ),
    ]
