# Generated by Django 4.1.4 on 2022-12-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terror', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrorist',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
