# Generated by Django 4.1.4 on 2022-12-28 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soliders', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiment',
            fields=[
                ('regiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('missions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
                ('soliders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soliders.soliders')),
            ],
        ),
    ]
