# Generated by Django 3.1.1 on 2023-01-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_auto_20230113_1552'),
        ('soliders', '0004_soliders_sol_id'),
        ('regiment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiment',
            name='missions_id',
        ),
        migrations.AddField(
            model_name='regiment',
            name='missions_id',
            field=models.ManyToManyField(to='missions.Mission'),
        ),
        migrations.RemoveField(
            model_name='regiment',
            name='soliders',
        ),
        migrations.AddField(
            model_name='regiment',
            name='soliders',
            field=models.ManyToManyField(to='soliders.Soliders'),
        ),
    ]
