# Generated by Django 3.1.1 on 2023-01-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soliders', '0006_leave_letter_form_is_approved'),
        ('missions', '0003_auto_20230113_1553'),
        ('regiment', '0002_auto_20230113_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiment',
            name='missions_id',
        ),
        migrations.AddField(
            model_name='regiment',
            name='missions_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='missions.mission'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='regiment',
            name='soliders',
        ),
        migrations.AddField(
            model_name='regiment',
            name='soliders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soliders.soliders'),
            preserve_default=False,
        ),
    ]
